### ISSUE TITLE
blank projects won't load ...

### ISSUE THREAD

**Issue by craftoid** [nodebox/live#34]
Hey there,  NodeBox Live rocks!
I started playing around and found that the blank template does not seem to work.
Here's the bug report ...

## Issue 34
When creating a new project and selecting the blank template (`Blank — An empty project, start from scratch`) the project cannot be opened.

### Screenshot of the error message:

<img width="755" alt="something-went-wrong" src="https://cloud.githubusercontent.com/assets/720669/23018722/5d006b66-f43f-11e6-8a26-9bffed75b34e.png">

### Raw XML of the project:

```
{
    "title": "blank",
    "color": "teal",
    "dependencies": {},
    "assets": {},
    "functions": []
}
```

**Comment by fdb** [comment]
This should be fixed now with the latest release: https://nodebox.live/bitcraftlab/blank

**Comment by craftoid** [comment]
Cool, thank you!
